services:
  python_3_10:
    stdin_open: true
    build: .
    shm_size: '16gb'
    container_name: 'python_3_11'
    working_dir: '/workspace'
    tty: true
    volumes:
    #  - ../src:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]